version: '3.9'
services:
   easyknowledge4u:
        build: .
        ports:
            - 8443:8443
        networks:
            - easyknowledge-network
            
   easyknowledge4u2:
        build: .
        ports:
            - 8444:8443
        networks:
            - easyknowledge-network  
            
   internalservice:
        image: serviciointerno:latest
        ports:
            - 8080:8080
        depends_on:
            - easyknowledge4u   
        networks:
            - easyknowledge-network
   haproxy:
      #build: ./Haproxy
      ports:
            - "2443:2443"
      image: haproxy:latest
      volumes:
              - "./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro"
      
networks:
    easyknowledge-network:
        driver: bridge