version: '3.9'
services:
  
       database:
        container_name: database
        image: mysql:8.0.25
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_USER=user
            - MYSQL_DATABASE=easyknowledge
            - MYSQL_PASSWORD=password
        ports:
            - 3307:3306
        networks: 
            - easyknowledge-network
       easyknowledge4u:
         container_name: easyknowledge4u
         build: .
         environment:
            - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/easyknowledge?useSSL=false&allowPublicKeyRetrieval=true
            
         depends_on:
            - database
         ports:
            - 8445:8443
         networks:
            - easyknowledge-network
            
       easyknowledge4u2:
        container_name: easyknowledge4u2
        build: .
        environment:
            - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/easyknowledge?useSSL=false&allowPublicKeyRetrieval=true 
            
        depends_on:
            - database
        ports:
            - 8446:8443
        networks:
            - easyknowledge-network  
              
       internalservice:
        container_name: internalservice
        image: serviciointerno:latest
        ports:
            - 8080:8080
        depends_on:
            - easyknowledge4u   
        networks:
            - easyknowledge-network
            
       haproxy:
        container_name: balanceador
       #build: ./Haproxy
        ports:
              - "8888:8080"
              - "9999:4443" 
             
        image: haproxy:latest
        volumes:
              - ./Haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro 
              - ./Haproxy/cert.pem:/usr/local/etc/ssl/cert.pem:ro 
              
        depends_on:
              - easyknowledge4u       
              - easyknowledge4u2
        networks:
            - easyknowledge-network      
networks:
    easyknowledge-network:
        driver: bridge
